---
title: "p8105_hw6_yx2858"
author: "Yueyi Xu"
date: "2023-11-28"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(modelr)
library(broom)
library(boot)
library(dplyr)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```



# Problem 2

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

### Create a bootstrap sample function

```{r}
set.seed(1)
boot_sample = function(df) {
  sample_frac(df, replace = TRUE)
}
```

### Create 5000 bootstrap samples

```{r}
boot_strap_df =
  weather_df |>
  modelr::bootstrap(n = 5000) |>
  mutate(
    models = map(strap, ~lm(tmax ~ tmin + prcp, data = .x)),
    beta = map(models, broom::glance),
    r2 = map(models, broom::tidy)
  ) |>
  unnest(beta, r2) |>
  dplyr::select(.id, term, estimate, r.squared) |>
  pivot_wider(names_from = term, values_from = estimate) |>
  rename(
    beta_0 = '(Intercept)',
    beta_1 = tmin,
    beta_2 = prcp
  )
```

### identify the 2.5% and 97.5% quantiles to provide a 95% confidence interval for r^2

```{r}
r_s = boot_strap_df |>
  select(r.squared) |>
  summarize(
    ci_low = quantile(r.squared, 0.025),
    ci_upp = quantile(r.squared, 0.975)
  )
```

print in table:

```{r}
r_s |>
  knitr::kable()
```

### Plot the distribution of r^2 estimate

```{r}
boot_strap_df |>
  select(r.squared) |>
  ggplot(aes(x = r.squared)) +
  geom_density() +
  labs(
    title = "Distribution of r-squared estimates",
    x = "r-squared estimates",
    y = "Density",
    subtitle = "5000 bootstrap samples"
  )
```





